# Generated by Django 4.2.1 on 2023-05-21 17:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CurrencyAddress',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('address', models.CharField(max_length=256)),
                (
                    'symbol',
                    models.CharField(
                        choices=[
                            ('BTC', 'Bitcoin'),
                            ('ETH', 'Ethereum'),
                            ('DOGE', 'Dogecoin'),
                            ('LTC', 'Litecoin'),
                            ('OMNI', 'Omni'),
                            ('DASH', 'Dash'),
                            ('QTUM', 'Qtum'),
                        ],
                        max_length=8,
                    ),
                ),
                ('number', models.PositiveIntegerField()),
                ('private_key_version', models.CharField(max_length=8)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_ts'],
                'indexes': [
                    models.Index(
                        fields=['symbol', 'private_key_version'],
                        name='currency_address_number_index',
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='currencyaddress',
            constraint=models.UniqueConstraint(
                fields=('symbol', 'number', 'private_key_version'),
                name='currency_address_number_unique',
            ),
        ),
    ]
